<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disney</name>
   <tag></tag>
   <elementGuidId>e70e020a-7471-4e54-a89d-4ab710ea2192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[4]/div/div/section/div/div[3]/a/div[2]/div[2]/ul/li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.w-75px</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo_disney.7277e89d.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid w-75px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[2]/div[4]/div[@class=&quot;py-main bg-gray-50&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;animated fadeInUp delayp9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4&quot;]/a[@class=&quot;card card-packages card-packages-lg animated fadeInUp delayp4&quot;]/div[@class=&quot;card-body w-btn&quot;]/div[@class=&quot;card-body-bottom&quot;]/ul[@class=&quot;icon-list mb-3&quot;]/li[@class=&quot;icon-list-item&quot;]/img[@class=&quot;img-fluid w-75px&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/section/div/div[3]/a/div[2]/div[2]/ul/li/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
   </webElementXpaths>
</WebElementEntity>
